### ISSUE TITLE
Language contibution [Spanis / Español]

### ISSUE THREAD

**Issue by Proxy-E23** [BuIlDaLiBlE/BetterHI3Launcher#3]
Any questions or problems I will try to answer as quickly as possible

Para mis amigos que hablan español si ven alguna incongruencia, falta de ortografía o si creen que hay una mejor forma de traducir algo por favor avisen para actualizarlo.

[TextStrings_en.cs.txt](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/files/6047741/TextStrings_en.cs.txt)

**Comment by BuIlDaLiBlE** [comment]
Thanks so much for your contribution! This was way faster than I expected :^)
I've fixed most of the formatting issues for you, but there are two things that need your attention:
1. Throughout the file, you seem to leave the word "launcher" as is, however in string `msgbox_uninstall_4_msg` you used the word "lanzador" instead. Should that be left alone or changed to "launcher" as well?
2. String `msgbox_fixsubs_5_msg` is left untranslated.

**Comment by Proxy-E23** [comment]
I'm sorry, I should have checked that and not just limited myself to translating.

1. initially I wanted to keep "lanzador" as a translation of "launcher" but I felt that it was strange, so I decided to keep it as "launcher". In Spanish it is more common to say "launcher" than "lanzador ".

this part was my mistake not having updated "lanzador" to "launcher", so yes, it should be left as "launcher".

2. the translation for  `msgbox_fixsubs_5_msg`  is: "Archivos de subtitulo".

**Comment by BuIlDaLiBlE** [comment]
The following strings are going to be added in the upcoming update. Can you please translate them as well?
```
textStrings.Add("introbox_title", "Welcome to Better Honkai Impact 3rd launcher!");
textStrings.Add("introbox_msg_1", "!!! IMPORTANT, PLEASE READ !!!");
textStrings.Add("introbox_msg_2", "Seems like this is your first time using the launcher. First of all, I'm glad you've decided to give it a try so in case you'd like to give feedback don't hesitate to do so.\nSecondly, it is important that if you used the official launcher to update the game and didn't launch it yet (to the point where you are on the bridge) you shouldn't use this launcher. Otherwise the launcher may detect your game version as old and make you have to download it again.\n\nRead all that? Great! If you already have the game installed just press the \"Download\" button and select your game folder. The launcher will detect your game and you won't have to download it again.");
```

**Comment by Proxy-E23** [comment]
```
textStrings.Add("introbox_title", "Bienvenido a Better Honkai Impact 3rd launcher!");
textStrings.Add("introbox_msg_1", ¡¡¡ IMPORTANTE, POR FAVOR LEA CUIDADOSAMENTE !!!");
textStrings.Add("introbox_msg_2", "Parece que esta es la primera vez que usas este launcher. En primer lugar, me alegra que hayas decidido probarlo, en caso de que quieras darnos tu opinión no dudes en hacerlo.\nEn segundo lugar, es importante que si ya has actualizado el juego con el launcher oficial y todavía no has iniciado el juego (hasta el punto donde estas en el puente) no deberias utilizar este launcher. De lo contrario, el launcher puede detectar la versión de tu juego como una antigua y hacer que tengas que descargar todos los archivos de nuevo.\n\n¿Leíste todo? ¡Genial! Si ya tienes instalado el juego sólo debes de pulsar la opción \"Descargar\"  y seleccionar la carpeta donde has instalado el juego. El launcher detectará el juego y no sera necesario de volver a descargarlo.");
```

**Comment by Proxy-E23** [comment]
Sorry for taking time to respond, I had not seen that translation was required for new strings

**Comment by Proxy-E23** [comment]
Sorry for the delay, yesterday it was too late and today I had a very busy day

**Comment by BuIlDaLiBlE** [comment]
It's ok, I'm not rushing 😅

**Comment by BuIlDaLiBlE** [comment]
Next update is a biggie. Those strings are going to be added, can you please translate them?
```
textStrings["button_running"] = "Running";
textStrings["button_generate"] = "Generate";
textStrings["contextmenu_repair"] = "Repair game files";
textStrings["progresstext_verifying_1"] = "Verifying game files...";
textStrings["progresstext_verifying_2"] = "Verifying game file {0}/{1}...";
textStrings["progresstext_generating_hash"] = "Generating hash for file {0}/{1}...";
textStrings["progresstext_zipping"] = "Adding file {0}/{1} to ZIP archive...";
textStrings["progresstext_fetching_hashes"] = "Fetching file hashes...";
textStrings["progresstext_downloaded_file"] = "Downloaded file {0}/{1}";
textStrings["repairbox_msg"] = "This will check every game file and attempt to repair if any is broken. It could take a while.\nContinue?";
textStrings["msgbox_repair_1_msg"] = "The version of the game installed differs from repair information on the server. Due to us having to update this information manually, it may not be available for some time.\nPlease try again later.";
textStrings["msgbox_repair_2_msg"] = "No files need any repairs.";
textStrings["msgbox_repair_3_msg"] = "Found {0} corrupted file(s). They need to be repaired by downloading them again.\nBecause technology is awesome, only the required files will be downloaded.\nContinue?";
textStrings["msgbox_repair_4_msg"] = "{0} file(s) successfully repaired.";
textStrings["msgbox_repair_5_msg"] = "{0} file(s) failed to be repaired. Consider checking your storage device, it may be faulty.";
textStrings["msgbox_repair_6_msg"] = "Going to generate a JSON file containing the list of game files and their hashes, then create a ZIP archive with those files.\nContinue?";
```

**Comment by Proxy-E23** [comment]
```
textStrings["button_running"] = "Corriendo";
textStrings["button_generate"] = "Generar";
textStrings["contextmenu_repair"] = "Reparar los archivos del juego";
textStrings["progresstext_generating_hash"] = "Generando hash para archivo {0}/{1}...";
textStrings["progresstext_zipping"] = "Añadiendo archivo {0}/{1} al archivo ZIP...";
textStrings["progresstext_fetching_hashes"] = "Obteniendo hashes de archivos...";
textStrings["progresstext_downloaded_file"] = "Archivo descargado {0}/{1}";
textStrings["repairbox_msg"] = "Esto comprobará todos los archivos del juego e intentará repararlos si alguno está roto. Esto podría tomar un tiempo.\n¿Continuar?";
textStrings["msgbox_repair_1_msg"] = "La versión del juego instalada difiere de la información de reparación en el servidor. Debido a que tenemos que actualizar esta información manualmente, es posible que no esté disponible durante algún tiempo..\nPor favor, inténtelo de nuevo más tarde.";
textStrings["msgbox_repair_2_msg"] = "Ningún archivo necesita reparaciones.";
textStrings["msgbox_repair_3_msg"] = "Encontrado {0} archivo(s) corrupto(s). Necesitan ser descargados de nuevo para ser reparados.\nDebido a que la tecnología es increíble, solo se descargarán los archivos necesarios..\n¿Continuar?";
textStrings["msgbox_repair_4_msg"] = "{0} Archivo(s) reparado con éxito.";
textStrings["msgbox_repair_5_msg"] = "{0} Archivo(s) no pudieron ser reparado(s). Considera revisar tu dispositivo de almacenamiento, puede estar defectuoso.";
```

**Comment by Proxy-E23** [comment]
hello.

I have corrected and adapted some of the translations to make them a little clearer and more understandable.

```
textStrings.Add("downloadcachebox_msg", "Seleccione si desea descargar la caché completa o solo los archivos numéricos.\nElija \"Caché completa\" Si presenta problemas al momento de actualizar los recursos del evento.\nElija \"Archivos numéricos\" si tiene problemas para actualizar la configuración (bucle de update settings).\nTenga en cuenta que actualmente no hay forma de recuperar automáticamente la última caché y tenemos que cargarla manualmente a un espejo.\nEspejo en uso: {0}.\nÚltima actualización de la caché: {1}.\nActual encargado del espejo {2}.");
textStrings.Add("msgbox_download_type_1_msg", "Esto cambiará el tipo de descarga de recursos del juego en un intento de solucionar el infame bucle de actualización que no permite ingresar al juego..\nSi esto no soluciona el problema, inténtelo de nuevo..\n¿Continar?");
textStrings.Add("contextmenu_web_profile", "Iniciar sesion en el sitio oficial de Honkai Impact");
textStrings.Add("contextmenu_language_system", "Predeterminado (Sistema Operativo)");
textStrings.Add("contextmenu_language_contribute", "¿Quieres ayudar?")
textStrings.Add("aboutbox_msg", "Bueno, es mucho más avanzado, ¿no?:^)\nEste proyecto se creo con la intención de que los capitanes tuvieran una mejor experiencia con el juego..\nBetterHI3Launcher no está afiliado a miHoYo y es completamente de código abierto..\nAgradecemos mucho todo el feedback.\nUn agradecimiento especial a los contribuidores de GitHub:\nSinsOfSeven - Contribución de resolución personalizada\nProxy-E23 - Traducción al idioma Español\nSpookyKisuy - Traducción al idioma portugués\nbulawin1 - Traducción al idioma Alemán\nKorewaLidesu - Traducción al idioma Vietnamita");
textStrings.Add("progresstext_error", "¡Ups! Algo salió mal :^(");
```

**Comment by BuIlDaLiBlE** [comment]
`contextmenu_web_profile` and `contextmenu_language_system` feel like too long compared to other text in the same place. Can it be shortened or better leave as is?

**Comment by Proxy-E23** [comment]
I tried to shorten it but I think it still feels a bit long

```
textStrings.Add("contextmenu_web_profile", "Abrir perfil en el sitio web");
textStrings.Add("contextmenu_language_system", "Predeterminado del sistema");
```

**Comment by BuIlDaLiBlE** [comment]
Actually, doesn't look bad. Maybe the second one is a bit long but still not horrendous. Thanks!

**Comment by BuIlDaLiBlE** [comment]
Translate these please?
```
textStrings["msgbox_download_type_2_msg"] = "Download type has been reset. Start the game and select \"HD assets\".";
textStrings["msgbox_download_type_3_msg"] = "Download type has already been reset. Start the game and select \"HD assets\".";
```

**Comment by Proxy-E23** [comment]
```
textStrings["introbox_msg"] = "Al parecer esta es la primera vez que usa este Launcher. Me alegra que haya decidido probarlo, en caso de que quiera darnos su opinión, no dude en hacerlo dando clic en el botón \"Opciones\"y seleccionando \"Enviar comentarios\".\nSi ya ha instalado el juego, presiona el botón \"Descargar\" y selecciona la ubicación donde lo ha instalado. TEl launcher detectara la instalación y no sera necesario descargarlo de nuevo.";

textStrings["msgbox_download_type_2_msg"] = "Se restableció el tipo de descarga. Inicie el juego y seleccione \"HD assets\".";

textStrings["msgbox_download_type_3_msg"] = "El tipo de descarga ya se ha restablecido. Inicie el juego y seleccione \"HD assets\".";

```

this string needs a fix

`textStrings.Add("button_running", "Corriendo");` to

`textStrings.Add("button_running", "Ejecutando");`

A few days later, but here it is. I am sorry  (っ˘̩╭╮˘̩)っ

**Comment by BuIlDaLiBlE** [comment]
More strings. No more need to rush, as I've implemented a way to update those without needing to release a new binary.
```
"msgbox_custom_background_1_msg": "You can select a file to be used as a background.\nIt can be an image or a video.\nRecommended resolution is {0} by {1} pixels.\nContinue?",
"msgbox_custom_background_2_msg": "Select what would you like to do with the background.",
"msgbox_custom_background_3_msg": "Selected file does not have the recommended resolution. You may still use it, but it will be stretched to the window size.\nContinue?",
"msgbox_custom_background_4_msg": "Please select another file.",
"msgbox_custom_background_5_msg": "Selected file is too large.\nYou can use files up to {0} in size.",
"msgbox_custom_background_6_msg": "There is not enough free space on your system drive to use the file.",
"msgbox_custom_background_7_msg": "Selected file is not in a supported format.",
"msgbox_custom_background_8_msg": "Failed to load selected file.",
"msgbox_custom_background_edit": "Change it",
"msgbox_custom_background_delete": "Reset to official",
"msgbox_download_cache_4_msg": "The cache is outdated either partially or fully.\nCheck the last update time for the exact date.\nDo you still want to continue?",
"msgbox_reset_game_settings_moved_msg": "This option has been moved to uninstallation.\nWould you like to go there now?",
"msgbox_unhandled_exception_msg": "Oops, something very bad has happened and the launcher must close. But you can help!\nThere is a log file you can send to help diagnose the error.\nDo you want to open the log file now?"
"msgbox_uninstall_1_msg": "Select what would you like to uninstall.",
"msgbox_uninstall_2_msg": "Are you sure you want to uninstall the following?",
"msgbox_uninstall_3_msg": "Are you really sure you want to uninstall the following? :^(",
"msgbox_uninstall_4_msg": "This action is irreversible.\nOnly do this if you are having problems with the game!\nAre you sure you want to continue?",
"msgbox_uninstall_6_msg": "Sucessfully uninstalled the following:"
```

**Comment by Proxy-E23** [comment]
```
"contextmenu_custom_background": "Establecer fondo personalizado",
"msgbox_custom_background_1_msg": "YPuede seleccionar un archivo para usarlo como fondo.\nDebe ser una imagen o un video.\nLa resolución recomendada es {0} por {1} pixeles.\nContinuar?",
"msgbox_custom_background_2_msg": "Seleccione qué le gustaría hacer con el fondo.",
"msgbox_custom_background_3_msg": "El archivo seleccionado no tiene la resolución recomendada. Aún puede usarlo, pero se estirara al tamaño de la ventana.\nContinuar?",
"msgbox_custom_background_4_msg": "Seleccione otro archivo.",
"msgbox_custom_background_5_msg": "El archivo seleccionado es demasiado grande.\nPuede utilizar archivos de hasta {0} en tamaño.",
"msgbox_custom_background_6_msg": "No hay suficiente espacio disponible en tu disco para usar el archivo.",
"msgbox_custom_background_7_msg": "El formato del archivo no es compatible.",
"msgbox_custom_background_8_msg": "Error al cargar el archivo seleccionado.",
"msgbox_custom_background_edit": "Cambialo,
"msgbox_custom_background_delete": "Regresar al oficial",
"msgbox_download_cache_4_msg": "La caché está desactualizada parcial o totalmente.\nVerifique la hora de la última actualización para conocer la fecha exacta.\n¿Todavía desea continuar?",
"msgbox_reset_game_settings_moved_msg": "Esta opción ha sido movido a desinstalación.\n¿Le gustaría ir allí ahora?",
"msgbox_unhandled_exception_msg": "!Oops¡, ha ocurrido algo muy malo y el lanzador debe cerrarse!. Pero puedes ayudarnos!\nHay un archivo de registro que puede enviar para ayudar a diagnosticar el error..\n¿Quiere abrir el archivo de registro ahora?",
"msgbox_uninstall_1_msg": "Seleccione lo que le gustaría desinstalar.",
"msgbox_uninstall_2_msg": "¿Está seguro que desea desinstalar lo siguiente?",
"msgbox_uninstall_3_msg": "¿Esta realmente seguro que desea desinstalar lo siguiente?:^(",
"msgbox_uninstall_4_msg": "Esta acción es irreversible.\n¡Haz esto solo si tienes problemas con el juego!\n¿Estás seguro de que quieres continuar?",
"msgbox_uninstall_6_msg": "Ha desinstalado con éxito lo siguiente:"
```

**Comment by Proxy-E23** [comment]
```
"contextmenu_custom_background": "Establecer fondo personalizado",
"msgbox_custom_background_1_msg": "Puede seleccionar un archivo para usarlo como fondo.\nDebe ser una imagen o un video.\nLa resolución recomendada es {0} por {1} pixeles.\nContinuar?",
"msgbox_custom_background_2_msg": "Seleccione qué le gustaría hacer con el fondo.",
"msgbox_custom_background_3_msg": "El archivo seleccionado no tiene la resolución recomendada. Aún así puede usarlo, pero se estirara al tamaño de la ventana.\nContinuar?",
"msgbox_custom_background_4_msg": "Seleccione otro archivo.",
"msgbox_custom_background_5_msg": "El archivo seleccionado es demasiado grande.\nPuede utilizar archivos de hasta {0} de tamaño.",
"msgbox_custom_background_6_msg": "No hay suficiente espacio disponible en el disco para usar este archivo.",
"msgbox_custom_background_7_msg": "El formato del archivo no es compatible.",
"msgbox_custom_background_8_msg": "Error al cargar el archivo seleccionado.",
"msgbox_custom_background_edit": "Cambialo,
"msgbox_custom_background_delete": "Regresar al oficial",
"msgbox_download_cache_4_msg": "La caché está desactualizada parcial o totalmente.\nVerifique la hora de la última actualización para conocer la fecha exacta.\n¿Todavía desea continuar?",
"msgbox_reset_game_settings_moved_msg": "Esta opción ha sido movida a desinstalación.\n¿Le gustaría ir allí ahora?",
"msgbox_unhandled_exception_msg": "!Oops¡, ha ocurrido algo muy malo y el launcher debe cerrarse!. Pero puede ayudarnos!\nHay un archivo de registro que puede enviar para ayudarnos a diagnosticar el error.\n¿Quiere abrir el archivo de registro ahora?",
"msgbox_uninstall_1_msg": "Seleccione lo que le gustaría desinstalar.",
"msgbox_uninstall_2_msg": "¿Está seguro que desea desinstalar lo siguiente?",
"msgbox_uninstall_3_msg": "¿Esta realmente seguro que desea desinstalar lo siguiente?:^(",
"msgbox_uninstall_4_msg": "Esta acción es irreversible.\n¡Haz esto solo si tienes problemas con el juego!\n¿Estás seguro de que quieres continuar?",
"msgbox_uninstall_6_msg": "Ha desinstalado con éxito lo siguiente:"
```

**Comment by BuIlDaLiBlE** [comment]
A few new strings!~
```
"msgbox_feature_not_available_msg": "This feature is not available for selected server.",
"msgbox_install_1_msg": "Select where would you like to install the game.",
"msgbox_move_1_msg": "Select where would you like to move the game.",
```
Also a part of `downloadcachebox_msg` was changed as well, I need this translated:
```
"Full cache" contains the entire cache, including event pictures and settings. "Numeric files" contains settings only, those files are updated most frequently.
```

**Comment by BuIlDaLiBlE** [comment]
In need of a translation again!
`The entire game cache will be checked and can be downloaded if needed. It can take a while.\nHi3Mirror is a project courtesy of {0}.\nContinue?`

**Comment by izac999** [comment]
Does this language still need translation?

**Comment by BuIlDaLiBlE** [comment]
Yes!

**Comment by BuIlDaLiBlE** [comment]
A couple of new ones.
```
"label_merging": "Merging",
"label_merged": "Merged {0}%",
"label_merge_speed": "Merge speed:",
"announcementbox_do_not_show": "Do not show me this next time",
```

**Comment by BuIlDaLiBlE** [comment]
Also, I have changed `msgbox_download_type_1_msg` from
```
This will reset game's resource download type in an attempt to fix the infamous update loop which does not let you enter the game.\nContinue?
```
to
```
This will reset game's resource download type and allow you to reselect which assets to download.\nContinue?
```
Can you please retranslate that?

**Comment by BuIlDaLiBlE** [comment]
Two new strings:
```
"contextmenu_open_screenshots_dir": "Open screenshots directory"
"msgbox_no_screenshot_dir_msg": "There are no screenshots. Go take some!"
```

**Comment by Proxy-E23** [comment]
"Hey, I'm back! It's been almost two years (I think) since the last time we talked. I've translated everything from the August 21st, 2021 message. Sorry for leaving this hanging, life got in the way, but I'm back now. Some of the translations may sound a bit odd as I didn't have context for the current state of the launcher. I'll be reinstalling the game in the coming days, and I'll let you know if anything needs updating."

```
"msgbox_feature_not_available_msg": "Esta característica no está disponible para el servidor seleccionado."
"msgbox_install_1_msg": "Seleccione dónde le gustaría instalar el juego."
"msgbox_move_1_msg": "Seleccione dónde le gustaría mover el juego."
```

`"Full cache" contiene todo el caché, incluyendo imágenes de eventos y configuraciones. "Archivos numéricos" contiene solo las configuraciones, esos archivos son actualizados con más frecuencia.`

```
"contextmenu_custom_launch_options": "Establecer opciones de lanzamiento personalizadas",
"msgbox_custom_launch_options_msg": "Los usuarios avanzados pueden ingresar opciones de lanzamiento personalizadas aquí.\nNota: Se aplican de forma independiente para cada servidor."
```

`"¿Deseas restablecer la información de instalación?"`

`Se comprobará todo el caché del juego y se podrá descargar si es necesario. Esto puede demorar un poco.\nHi3Mirror es un proyecto cortesía de {0}.\n¿Deseas continuar?`

```
"label_merged": "{0}% Combinado",
"label_merge_speed": "Velocidad de combinación:",
"announcementbox_do_not_show": "No mostrar esto la próxima vez"
```

`¿Te gustaría restablecer la configuración de descarga de recursos del juego para poder volver a elegir qué elementos descargar? \n¿Deseas continuar?`

```
"contextmenu_open_screenshots_dir": "Abrir directorio de capturas de pantalla"
"msgbox_no_screenshot_dir_msg": "No hay capturas de pantalla. ¡Ve a tomar algunas!"
```

**Comment by BuIlDaLiBlE** [comment]
Hey glad to have you back @Proxy-E23! Yeah, a lot of updates happened since then...
Btw, in `¿Te gustaría restablecer la configuración de descarga de recursos del juego para poder volver a elegir qué elementos descargar? \n¿Deseas continuar?` the first sentence is a question? But then there is another question at the end, looks a bit odd. Ideally the first sentence should be a statement, or I can just remove the second question then.

**Comment by Proxy-E23** [comment]
It was my mistake to interpret the sentence, I thought that `\n¿Deseas continuar?` was a new dialogue box to request confirmation of the previous action.

This would be the most correct.
`Esto restablecerá el tipo de descarga de los recursos del juego y te permitirá volver a seleccionar qué elementos descargar. \n¿Deseas continuar?
`
